---
- name: Power on
  gather_facts: false
  hosts: localhost
  tasks: 
  - name: Set the state of a virtual machine to powered-on
    community.vmware.vmware_guest_powerstate:
      hostname: 10.206.112.50
      username: administrator@pureczebc.local
      password: "{{ password }}"
      folder: /jacint
      name: jj-ORA-1
      state: powered-on
      validate_certs: false
      force: true
    delegate_to: localhost
    register: deploy
  - name: Set the state of a virtual machine to powered-on
    community.vmware.vmware_guest_powerstate:
      hostname: 10.206.112.150
      username: administrator@vsphere.local
      password: "{{ password }}"
      folder: /jacint
      name: jj-ORA-2
      state: powered-on
      validate_certs: false
      force: true
    delegate_to: localhost
    register: deploy
...
