---
- name: upgrade kubernetes cluster
  hosts: "{{ master }}"
  gather_facts: false
  tasks: 
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes

  - name: unhold kubeadm
    ansible.builtin.dpkg_selections:
      name: kubeadm
      selection: install

  - name: kill apiserver
    command: killall -s SIGTERM kube-apiserver

  - name: upgrade kubeadm
    ansible.builtin.apt:
      name: kubeadm={{ version }}-1.1
      state: present

  - name: hold kubeadm
    ansible.builtin.dpkg_selections:
      name: kubeadm
      selection: hold

  - name: wait for apiserver
    command: sleep 240

  - name: kubeadm upgrade
    command: kubeadm upgrade apply --yes v{{ version }}

  - name: drain the node
    command: kubectl drain "{{ inventory_hostname }}" --ignore-daemonsets --delete-emptydir-data

  - name: unhold kubelet
    ansible.builtin.dpkg_selections:
      name: kubelet
      selection: install

  - name: unhold kubectl
    ansible.builtin.dpkg_selections:
      name: kubectl
      selection: install

  - name: upgrade kubelet
    ansible.builtin.apt:
      name: kubelet={{ version }}-1.1
      state: present

  - name: upgrade kubectl
    ansible.builtin.apt:
      name: kubectl={{ version }}-1.1
      state: present

  - name: hold kubelet
    ansible.builtin.dpkg_selections:
      name: kubelet
      selection: hold

  - name: hold kubectl
    ansible.builtin.dpkg_selections:
      name: kubectl
      selection: hold

  - name: daemon reload
    command: systemctl daemon-reload

  - name: restart kubelet
    command: systemctl restart kubelet

  - name: uncordon the node
    command: kubectl uncordon "{{ inventory_hostname }}"

...

