- name: copy sources.list
  gather_facts: false
  hosts: "{{ cluster }}"
  tasks: 
  - name: copy sources.list
    copy:
      src: kubernetes-sources.list
      dest: /etc/apt/sources.list.d/kubernetes.list
      owner: root
      group: root
      mode: 0644
  
