---
- name: delete vm
  gather_facts: false
  hosts: localhost
  tasks: 
  - name:  Delete a virtual machine 
    community.vmware.vmware_guest:
      hostname: purecz-vc-01
      username: administrator@pureczebc.local
      password: "{{ password }}"
      datacenter: PureCZ-Site1
      state: absent
      cluster: One
      folder: /jacint
      name: "{{ vmname }}"
      validate_certs: false
    delegate_to: localhost
...

