---
- name: Get VM info
  gather_facts: false
  hosts: localhost
  vars: 
    ansible_python_interpreter: /usr/bin/python3.11
  tasks: 
  - name: Gather all VMs from folder 
    community.vmware.vmware_vm_info:
      hostname: 10.206.112.50
      username: administrator@pureczebc.local
      password: "{{ password }}"
      folder: /PureCZ-Site1/vm/jacint
      validate_certs: false
      show_attribute: true
    delegate_to: localhost
    register: vm_info
...

