---
- name: Power Off VM
  gather_facts: false
  hosts: localhost
  vars: 
    ansible_python_interpreter: /usr/bin/python3.11
  tasks: 
  - name: Set the state of a virtual machine to powered-off
    community.vmware.vmware_guest_powerstate:
      hostname: 10.206.112.50
      username: administrator@pureczebc.local
      password: "{{ password }}"
      folder: /jacint
      name: "{{ vmname }}"
      state: powered-off
      validate_certs: false
      force: false
    delegate_to: localhost
    register: deploy

...
