---
- name: push kube config
  hosts: '{{ cluster }}'
  gather_facts: false
  tasks: 
    - name: copy config to root
      copy: 
        src: /home/jacint/.kube/config
        dest: /root/.kube/config
        owner: root
        group: root
        mode: '0640'
    - name: copy config to user
      copy: 
        src: /home/jacint/.kube/config
        dest: /home/jacint/.kube/config
        owner: jacint
        group: jacint
        mode: '0640'

...
