- name:
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create new pod 
      purestorage.flasharray.purefa_pod:
        name: jj-ans
        fa_url: x70a
        api_token: "{{ x70atoken }}"
        state: present

    - name: Stretch a pod 
      purestorage.flasharray.purefa_pod:
        name: jj-ans
        stretch: PureCZ-X70-B
        fa_url: x70a
        api_token: "{{ x70atoken }}"

    - name: Create new volume 
      purestorage.flasharray.purefa_volume:
        name: "{{ volname }}"
        size: 100G
        fa_url: x70a
        api_token: "{{ x70atoken }}"
        state: present

    - name: Map host to volume 
      purestorage.flasharray.purefa_host:
        name: jjRHEL
        volume: "{{ volname }}"
        fa_url: x70a
        api_token: "{{ x70atoken }}"

    - name: Map host to volume 
      purestorage.flasharray.purefa_host:
        name: jjRHEL
        volume: "{{ volname }}"
        fa_url: x70b
        api_token: "{{ x70btoken }}"
