---
- name: push kube config
  hosts: '{{ cluster }}'
  gather_facts: false
  tasks: 
    - name: copy config
      copy: 
        src: /home/jacint/.kube/config
        dest: /etc/kubernetes/admin.conf
        owner: root
        group: kube
        mode: '0640'

...
